### ISSUE TITLE
Story Map Series (tabbed) cannot embed Operation Dashboard web app?

### ISSUE THREAD

**Issue by Nataliya1** [Esri/map-series-storytelling-template-js#27]
I already posted the issue under Operation Dashboard: 

https://github.com/Esri/dashboard-samples/issues/3

So basically when I try to add the Operation Dashboard web app as a website to one of the tabs in my Map serier, it just would not load. (note*... my operation dashboard app loads fine if I add it to the Map Journal Template). 

Is it a bug, or am I missing something.

Thank you,
Nataliya

**Comment by glazou** [comment]
Hey,

I made a test and it seems to work. This may be an issue because your story map is using a different protocol (http or https) than your dashboard.

We have a blog post explaining this in detail, see https://blogs.esri.com/esri/arcgis/2016/04/14/embedding-apps-and-websites-in-story-maps/. 

You can start by trying to change the URL of the dashboard in the story map to use `http` if it was `https` or vice versa.

**Comment by Nataliya1** [comment]
@glazou, 

Thank you for the blog article. That was it. It was the issue with http vs. https. My OpsDashboard map was http, once I switched url to https it loaded in the Map Series Tab. Thanks, again. Nataliya.
