### ISSUE TITLE
YouTube full-screen control makes the app go full-screen

### ISSUE THREAD

**Issue by acarroll51** [Esri/map-series-storytelling-template-js#4]
In Chrome, clicking on the "expand" control on a YouTube video embedded in a popup sometimes causes the Map Series to go full-screen instead of the video. After collapsing the full-screen view the popups don't work until the story is reloaded. See the third tab of
http://story.maps.arcgis.com/apps/MapSeries/?appid=79798a56715c4df183448cc5b7e1b999

**Comment by glazou** [comment]
Seems ok for me in Chrome on Windows. Could you capture a screenshot?
The full screen button is part of Youtube embed, I have no control over it. The expected behavior is that the video will go full screen hover the app, no way around this.

Can you repro the issue in Map Viewer? http://www.arcgis.com/home/webmap/viewer.html?webmap=d295eb613ebb4dc4b7a3fa51d82f5fe1

Let's try to debug the issue but there is a URL parameter that allow to get rid of the full screen button
https://www.youtube.com/embed/oEQ_Wprvh4o => https://www.youtube.com/embed/oEQ_Wprvh4o?fs=0

**Comment by acarroll51** [comment]
Lee saw it yesterday in Chrome on his PC. It doesn't occur in the map viewer. I'd very much rather keep the full-screen option for viewing the videos, since they're so puny inside the popup. Here's what it looks like:

![screen shot 2015-01-15 at 11 11 20 am](https://cloud.githubusercontent.com/assets/5605521/5761164/88e2bc62-9ca7-11e4-8cc3-069a8e594861.png)

**Comment by glazou** [comment]
ok got it. It happen when you click on a marker that is under the description panel (red zone) when you first load the tab. If you click on any other marker before you won't have the issue has the one in the red area are not clickable.

![image](https://cloud.githubusercontent.com/assets/994078/5761409/25375054-9c90-11e4-836e-1f89abb5e10b.png)

The marker in the red area should be clickable.

Not sure how I will fix this but on the list for next release.When do you plan to release that story?

**Comment by acarroll51** [comment]
Mid-February. Thanks Greg.
